version: '3.1'

services:
  mssqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: ms-sqlserver-2019
    ports:
      - 1433:1433
    network_mode: bridge
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_PID=Developer
      - SA_PASSWORD=DockerSql2019!