version: '3.1'

volumes:
  portainer_data:
    name: portainer_data

networks:
  portainer_network:
    name: portainer_network

services:
  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    privileged: true
    ports:
      - 8000:8000
      - 9443:9443
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - portainer_network
    restart: unless-stopped
