version: "3"

volumes:
  npm-data:
    name: npm-data
  npm-ssl:
    name: npm-ssl
  npm-db:
    name: npm-db

networks:
  frontend:
    external: true
  backend:
    external: true

services:

  npm-app:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: npm-app
    restart: unless-stopped
    ports:
      - '80:80' # Public HTTP Port
      - '81:81' # Admin Web Port
      - '443:443' # Public HTTPS Port
    environment:
      DB_MYSQL_HOST: npm-db
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "npm"
      DB_MYSQL_PASSWORD: "npm_docker"
      DB_MYSQL_NAME: "npm"
    volumes:
      - npm-data:/data
      - npm-ssl:/etc/letsencrypt
    depends_on:
      - npm-db
    networks:
      - frontend
      - backend

  npm-db:
    image: 'jc21/mariadb-aria:latest'
    container_name: npm-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 'npm'
      MYSQL_DATABASE: 'npm'
      MYSQL_USER: 'npm'
      MYSQL_PASSWORD: 'npm_docker'
    volumes:
      - npm-db:/var/lib/mysql
    networks:
      - backend
